name: Code Coverage

on:
  pull_request:
    branches: [ master ]
    
jobs:
  test:
    name: Code Coverage Report
    uses: codecov/codecov-action@v3
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
