name: Code Coverage
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.30.0"
      - name: Run tests
        run: deno test --allow-read --allow-env
      - name: Generate lcov
        run: deno coverage ./coverage/ --lcov --exclude="test\\.(ts|js)|wasm\\.js|testdata" > coverage.lcov
      - name: Upload Code Coverage Report
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage.lcov
