name: Code Coverage
on: [push, pull_request]
jobs:
  test:
    steps:
      - name: Code Coverage Report
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
