name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  chomp:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.40.0"
      - name: Check format
        run: deno task test:fmt
      - name: Check lint
        run: deno lint
      - name: Run tests generating coverage
        run: deno task test:coverage
      - name: Generate lcov report
        run: deno task coverage > cov.lcov
      - name: upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./cov.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
